#Site config
title: 思考生活
SEOTitle: 思考生活 | ThinkLife Blog
header-img: img/books/backgroud.jpg
email: ads1223@gmail.com
description: "Think-life - 思考而创作"
keyword: "曹志龙的博客, CaoZhiLong Blog, 博客, 个人网站, 云计算, docker, openstack"
google_analytics: 
url: "http://caozhilong.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
#weibo_username:     caozhilong
#zhihu_username:     caozhilong
github_username:    caozhilong
#twitter_username:  caozhilong
#facebook_username:  caozhilong

#plugins


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# plugins: [jekyll-paginate]
plugins:
  - jekyll-paginate 
  - jekyll-gist


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: xasa2q

# Duoshuo settings
#duoshuo_username: caozhilong
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


gitbooks: [
    {
        head_img: "/img/books/gitbook.jpg",
        title: "gitbook | 学习GitBook的安装过程",
        descr: "Markdown语法写文档时的畅快感，想把团队项目文档都用markdown来写，然后能够在网上分享,团队合作",
        href: "https://caozhilong.github.io/gitbook/index.html"
    },
    {
        head_img: "/img/books/machineLearning.jpg",
        title: "machLearning | 学习人工智能",
        descr: "建构能够跟人类似甚至超越的推理、知识、规划、学习、交流、感知、移动和操作物体的能力等[6]。强人工智能目前仍然是该领域的长远目标[7]。目前强人工智能已经有初步成果，甚至在一些视频辨识、语言分析、棋类游戏等等单方面的能力达到了超越人类的水平，而且人工智能的通用性代表着，能解决上述的问题的是一样的AI程序，无须重新开发算法就可以直接使用现有的AI完成任务，与人类的处理能力相同，但达到具备思考能力的统合强人工智能还需要时间研究，比较流行的方法包括统计方法，计算智能和传统意义的AI。目前有大量的工具应用了人工智能，其中包括搜索和数学优化、逻辑推演。而基于仿生学、认知心理学，以及基于概率论和经济学的算法等等也在逐步探索当中。 思维来源于大脑，而思维控制行为，行为需要意志去实现，而思维又是对所有数据采集的整理，相当于数据库，所以人工智能最后会演变为机器替换人类",
        href: "https://caozhilong.github.io/machLearning/index.html"
    },
    {
        head_img: "https://caozhilong.github.io/incubator-dubbo-docs/dubbo-dev-book/sources/images/dubbo-framework.jpg",
        title: "dubbo | dubbo官网提供的文档",
        descr: "这篇文档的目标读者是对 dubbo 源码、设计有兴趣的，或者有意愿加入 dubbo 开发的人群。主要涵盖了 dubbo 的框架设计、扩展机制、编码规范、版本管理、构建等话题。",
        href: "https://caozhilong.github.io/incubator-dubbo-docs"
    },
    {
        head_img: "https://docs.docker.com/machine/img/machine.png",
        title: "Docker | Docker — 从入门到实践",
        descr: "Docker 是个划时代的开源项目，它彻底释放了计算虚拟化的威力，极大提高了应用的维护效率，降低了云计算应用开发的成本！使用 Docker，可以让应用的部署、测试和分发都变得前所未有的高效和轻松！无论是应用开发者、运维人员、还是其他信息技术从业人员，都有必要认识和掌握 Docker，节约有限的生命。",
        href: "https://yeasy.gitbooks.io/docker_practice"
    },
    {
        head_img: "http://www.ruanyifeng.com/blogimg/asset/2017/bg2017122701.jpg",
        title: "blockchain | blockchain — 区块链技术指南",
        descr: "区块链技术是现代金融科技（Fintech）领域的一项重要技术创新",
        href: "https://yeasy.gitbooks.io/blockchain_guide/content/index.html"
    },
    {
        head_img: "/img/books/spider.jpg",
        title: "Python3网络爬虫开发实战",
        descr: "Python3网络爬虫开发实战是一个爬虫与反爬虫的对决",
        href: "https://germey.gitbooks.io/python3webspider//index.html"
    },
    {
        head_img: "http://www.pinginglab.net/files/default/2018/08-18/225003bbb999074160.jpg",
        title: "Burp Suite 实战指南",
        descr: "刚接触web安全的时候，非常想找到一款集成型的渗透测试工具，找来找去，最终选择了Burp Suite",
        href: "https://t0data.gitbooks.io/burpsuite/content/chapter1.html"
    },
    {
        head_img: "http://img1.imgtn.bdimg.com/it/u=2463829054,637145907&fm=26&gp=0.jpg",
        title: "Android Studio 使用艺术",
        descr: "很多做Android开发的同学都关注技术，但我感觉对于一个开发者来说，工具的使用非常重要，可以提高编码速度，可以让更多的时间花在逻辑上",
        href: "https://as.quanke.name/前言.html"
    }
]


# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me

#pager settings
pager_previous_label: 上一篇
pager_next_label: 下一篇
feature_tag_label: 类别标签
tag_label: 标签

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "记录，学习，分享，成长。"
sidebar-avatar: /img/avatar-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value

catalog: true

# Friends
friends: [
    {
        title: "GeoServer | 开源地图渲染",
        href: "http://geoserver.org/"
    },
    {
        title: "kafaka |分布式流式平台",
        href: "http://kafka.apache.org"
    },
    {
        title: "activemq | 高可用的消息平台",
        href: "http://kafka.apache.org"
    }
]
